apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: echo-service
  namespace: apps
  labels:
    app: echo-service
spec:
  selector:
    matchLabels:
      app: echo-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
